### ISSUE TITLE
Attempting to (un)install and test

### ISSUE THREAD

**Issue by jamitupya** [goavega-software/suitecrm-azure-ad#1]
I installed this in a test instance to see if it worked, very interesting project and see lots of benefit to this if i can get it working :-)

plugin installs without complaint, can get into the settings page and configure what looks correct. click apply, start testing. 

1) when authenticating it seems to work well (goes to the O365 process+MFA, etc), however the redirect does not actually log the user in. it merely redirects back to the logon page.
2) when i have gone to remove and uninstall, it has gone well, however now i can not log into the CRM instance at all. seems that upon uninstall you don't change the authentication provider back to its previous setting in the configs?

just working through those 2 pieces if you had any ideas?

**Comment by sn123** [comment]
@jamitupya - can you let me know the version of SuiteCRM that you're using?

**Comment by jamitupya** [comment]
@sn123 Currently - 7.11.13, in the process of upgrading to 7.11.15 in the next 2 hours that should be done and will retest.

edit: apologies, its 7.11.*, in the process of upgrading to 7.11.13. that was completed and i just attempted again with different result. i'm now getting a token error so will deal with that and revert. positive thoughts :-)

**Comment by sn123** [comment]
ok let me know - 7.11.13 is what we use and have tested against.

**Comment by sn123** [comment]
@jamitupya closing this issue for now. Please reopen if required.
