### ISSUE TITLE
SSO not working -  Button doen't work

### ISSUE THREAD

**Issue by Rebz95** [goavega-software/suitecrm-azure-ad#2]
Hello,

the SSO button is not working.

After the configuration the button appears on login, but does not work.

It does not matter what I use for the Client/ Tenant ID, it does nothing.

I hope this will be fixed soon.

Best regards

**Comment by sn123** [comment]
Few details please:

1. Version of SuiteCRM
2. Which browser are you trying on?

**Comment by Rebz95** [comment]
I'm using the bitnami docker image: 7.11.5 (https://hub.docker.com/r/bitnami/suitecrm/tags)
and I tried it with different browsers (Firefox, Chrome, Edge, IE).

**Comment by sn123** [comment]
do you mean 7.11.15 instead of 7.11.5, and can you detail out the actual behavior a bit? Till where does it work, does it successfully install the plugin but the admin screens don't work? Or the admin screens work but the actual login screen doesn't do anything? 
Any console errors logged in JS console?

**Comment by Rebz95** [comment]
Now i am redirected by this button.The problem was that I had an empty space before my tenant ID. The problem of the button seems to be solved.

Unfortunately, SuiteCRM will only login through Azure, if there is an user with the same name (not email) registered as the azure email address.
What I mean is if I want to login with the Azure User "Test" with mail address: test@onmicrosoft.com
SuiteCRM says
"Sorry, this "test@onmicrosoft.com" user does not exist in CRM."

It will only sign in me if I created a user with name "test@onmicrosoft.com", do you know a solution for this?

**Comment by sn123** [comment]
That seems to be an issue with configuration, we try to match email address stored at SuiteCRM with the userName returned back by Azure AD:

https://github.com/goavega-software/suitecrm-azure-ad/blob/843ed3dde4470a4df1ac503b2ffbe287ee81d39d/SugarModules/modules/Users/Login.php#L280

Integration with Azure AD is done using browser side MSAL.js, you can perhaps try out their sample to see if that is returning correct value or not.

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser

Sample -
https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2

**Comment by Rebz95** [comment]
The Username has to match the Mail from Azure.

Thank you for your fast response and help 👍
