### ISSUE TITLE
user_name needs to be email-address

### ISSUE THREAD

**Issue by Mephisztoe** [goavega-software/suitecrm-azure-ad#3]
The setup instructions say:
"The plugin hides the default login box once it is enabled (JS only) so make sure that **all users's primary email addresses (not username) match users in Azure AD**."

This didn't work however.

The suitecrm.log also says:
Query:SELECT users.* FROM users  WHERE user_name = 'abc@defghi.jkl' AND deleted=0 LIMIT 0,1

I opened Heidi and changed my user_name in table users from abc to abc@defghi.jkl and that did the trick.

**Comment by sn123** [comment]
Weird, what version of Suite are you using?

**Comment by Mephisztoe** [comment]
Version 7.11.15
Sugar Version 6.5.25 (Build 344)

**Comment by sn123** [comment]
Maybe I was smoking something when I wrote the README. Looking at ```retrieve_user_id()``` (http://phpcrossref.com/xref/sugarcrm/modules/Users/User.php.html) implementation of Sugar, it does match based on the user_name field :). I'll update the readme.

```php
public function retrieve_user_id(
           $user_name
           )
       {
           $userFocus = new User;
           $userFocus->retrieve_by_string_fields(array('user_name'=>$user_name));
           if ( empty($userFocus->id) )
               return false;
   
           return $userFocus->id;
       }
```
> 
> 
> Version 7.11.15
> Sugar Version 6.5.25 (Build 344)

**Comment by Mephisztoe** [comment]
;-)

Doesn't matter. It works. And I am happy. First I noticed that SuiteCRM doesn't support AzureAD and tried to get SAML working... which was a rather frustrating experience. Then I found your extension and after struggling with the configuration I got it to work. It's brilliant! Thank you so much.

If this is okay with you, here's a suggestion:
In case you misconfigure anything, you cannot login using the "local" account anymore. For example: I didn't read the instructions properly and forgot to add the login-url to the tenant ID, but entered the ID only (though that would be sufficient). It took a while and some debugging to find out the root of the problem that was caused by this.

Maybe it would be nice if there was some kind of textlink anywhere on the page that allows to switch back to the local login method.

**Comment by sn123** [comment]
Do you mind adding this part as another issue? This issue is resolved and already closed, thanks!

> In case you misconfigure anything, you cannot login using the "local" account anymore. For example: I didn't read the instructions properly and forgot to add the login-url to the tenant ID, but entered the ID only (though that would be sufficient). It took a while and some debugging to find out the root of the problem that was caused by this.
> 
> Maybe it would be nice if there was some kind of textlink anywhere on the page that allows to switch back to the local login method.
