### ISSUE TITLE
invalid package

### ISSUE THREAD

**Issue by zebra2021** [goavega-software/suitecrm-azure-ad#5]
hello,

When I download your package and upload it to SuiteCRM(Install plug-in using Module Loader, Admin > Module Loader) , the system displays “invalid package”. I tried it with different browsers (Firefox, Chrome, Edge, IE),but it dose not work.

SuiteCRM Version 7.11.8
Sugar Version 6.5.25 (Build 344)

Best regards

**Comment by sn123** [comment]
Can you try upgrading to SuiteCRM version 7.11.13 and let me know if that works?

**Comment by zebra2021** [comment]
hello，
I upgraded the SuiteCRM to 7.11.18，And the installation was successful, but when I finished configuring the ID (the figure below is my configuration), then I try to log in, an error occurred.
![P2](https://user-images.githubusercontent.com/79627565/109489891-76c81400-7ac2-11eb-9a00-2f3ecd5deaf6.jpg)

**Comment by sn123** [comment]
please make sure on your Azure AD application you have added 192.168.x.x as a valid redirect URI as per doc here:
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration

**Comment by zebra2021** [comment]
the Tenant Id is wrong,now I've fixed it, And the login was successful！
Now the problem is that the Chinese language pack installed before is not effective. When I log in with azure ad, no matter what language I choose, the interface will be English after I log in.
![P1](https://user-images.githubusercontent.com/79627565/109939179-c3526000-7d0b-11eb-85b0-a672284cefec.png)
![P2](https://user-images.githubusercontent.com/79627565/109939495-15938100-7d0c-11eb-92f9-e649695f07a5.png)
